services:
        jenkins:
                image: jenkins/jenkins:lts-jdk17
                container_name: mtntJenkins
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - /var/lib/docker/volumes/410a4a2ebb4572a91196c1eb798b8db6fea4b9d64304f458c30bac5b39690c21/_data:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/bin/docker:/usr/bin/docker
                environment:
                        JAVA_OPTS: "-Djava.awt.headless=true"

