services:
  db:
    image: mysql:8.0
    container_name: mtnt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mdnd    # 루트 비밀번호
      MYSQL_DATABASE: myground           # 초기 데이터베이스 생성
      MYSQL_USER: mtnt              # 사용자 생성
      MYSQL_PASSWORD: mdnd         # 사용자 비밀번호
    ports:
      - "3306:3306"                         # MySQL 포트 매핑
    volumes:
      - db_data:/var/lib/mysql              # MySQL 데이터 볼륨
      - ./myground.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 스크립트

volumes:
  db_data:
    driver: local
