services:
        redis:
                image: redis:latest
                container_name: MTNT-redis
                ports:
                        - "6379:6379"
                volumes:
                        - redis-data:/data
                        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
                networks:
                        - mtnt-network
                command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        mysql:
                image: mysql:8.0
                container_name: MTNT-mysql
                environment:
                        MYSQL_ROOT_PASSWORD: mdnd
                        MYSQL_DATABASE: myground
                        MYSQL_USER: mtnt
                        MYSQL_PASSWORD: mdnd
                ports:
                        - "3306:3306"
                volumes:
                        - mysql-data:/var/lib/mysql
                        - ./mysql/myground_0801.sql:/docker-entrypoint-initdb.d/init.sql
                networks:
                        - mtnt-network
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
                container_name: MTNT-elasticsearch
                environment:
                        - discovery.type=single-node
                ports:
                        - "9200:9200"
                volumes:
                        - es-data:/usr/share/elasticsearch/data
                networks:
                        - mtnt-network

volumes:
        redis-data: 
        mysql-data: 
        es-data: 

networks:
        mtnt-network:
                driver: bridge
