services:
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
                container_name: mtnt-elasticsearch
                environment:
                        - discovery.type=single-node
                ports:
                        - "9200:9200"
                volumes:
                        - es-data:/usr/share/elasticsearch/data
volumes:
        es-data:
                driver: local
